### ISSUE TITLE
Closing a child dialog within a parent dialog closes the parent dialog as well

### ISSUE THREAD

**Issue by Spenstar** [fs-webdev/fs-dialog#103]
Our [fs-edit-record](https://github.com/fs-webdev/fs-edit-record) component uses `fs-modal-dialog` to display its contents. We are now considering using `fs-anchored-dialog` to display helps similar to the field helps in the Indexing app. Although, whenever `close()` is called on the anchored dialog, the parent modal dialog is also closed.

One way would be to add an attribute that toggles bubbling of events.

Another way would be to either provide or auto generate a UUID for each dialog component created. Then when a dialog is closed, the event will use that UUID to only close that respective dialog.

**Comment by rosemariesadler** [comment]
One of the common reasons for this happening is not giving the anchored dialog a focusBackElement when it opens, or the focusBackElement that is passed to it is not actually a focusable element. I've seen this work properly before - have you checked on the focusBackElement?

**Comment by Spenstar** [comment]
I'll look it to that and report back. Thanks!

**Comment by rosemariesadler** [comment]
Turns out that this was not an issue with the fs-anchored-dialog being inside an fs-modal-dialog.

For those who care what was causing the issue in this case, here's a snippet of my conversation with @Spenstar that sums up the problem:

okay, so here is what happens: https://github.com/fs-webdev/fs-edit-record/blob/spenstar/modals/fs-edit-record.html#L27 is setting up an event listener for the fs-dialog-close event - the parent dialog still gets the children's close event, so what I would recommend is adding a check here: https://github.com/fs-webdev/fs-edit-record/blob/spenstar/modals/fs-edit-record.html#L123 to only hide the dialog if the event is coming from the particular dialog you want to hide instead of a child. alternatively, the observer for `visible` may not need to close the dialog https://github.com/fs-webdev/fs-edit-record/blob/spenstar/modals/fs-edit-record.html#L104 and may only need to open it - not sure all the nuances of what all the code does.
