### ISSUE TITLE
fs-modal-dialog appears blurry on large screens

### ISSUE THREAD

**Issue by dcravenus** [fs-webdev/fs-dialog#72]
The `fs-modal-dialog` appears blurry on large screens. It appears the CSS transform scale blurs the modal.

Blurry Modal:
![screen shot 2018-03-14 at 10 21 18 am](https://user-images.githubusercontent.com/4764559/37415681-a034c07e-2771-11e8-95a8-933707f5b7be.png)

Same Modal on Laptop Screen:
<img width="669" alt="screen shot 2018-03-14 at 10 21 56 am" src="https://user-images.githubusercontent.com/4764559/37415682-a04f47b4-2771-11e8-8482-ca8578ceeac1.png">

**Comment by rosemariesadler** [comment]
We decided that we are not going to fix this - there is not a clean and performant way to fix this for all dialogs.

This issue is really a webkit bug dealing with css transforms (not just scale, but also translate). When there is a height or width that is an odd number of pixels, that is when the blurring happens. To fix this, you can set an explicit even-numbered height and width on your dialogs. 

We considered several solutions. First we thought about removing the transforms, but removing the transforms didn't allow us to center the dialog vertically in our current web component structure. The only way to change our positioning to not require transforms would require us to have a wrapper around the dialog just for positioning, and the only way to do that is to make all consumers add this wrapper to their dom.

The second solution we considered was adding explicit height to the dialog when a) it is opened b) the window is resized, and c) any of the dom content gets changed (very unperformant).

We did try all the css hacks that the internet gave us (translateZ(0), font-smoothing, transform-origin, fliter: blur(0), zoom/scale adjustments, backface-visibility, perspective, and maybe a few others I can't remember right now) and were not able to find any that worked.
