### ISSUE TITLE
opened attribute is read-only

### ISSUE THREAD

**Issue by justincy** [fs-webdev/fs-dialog#89]
Adding the attribute does not properly display the dialog.
Removing the attribute does not properly hide the dialog.

That's probably intentional but it wasn't clear from the docs that the methods had to be used instead of the attribute.

**Comment by rosemariesadler** [comment]
That is definitely intentional - which part of the docs was unclear? The demo page has code samples and they all use the open function, not the attribute. Do we need to add jsdocs to the attribute saying that it's read only? Would that make it clear enough? We'll update the docs with whatever info is needed to make it clearer.

**Comment by justincy** [comment]
I think that updating the jsdocs for the opened attribute would work. Because of the [web components catalog](https://www.webcomponents.org/), I'm accustomed to looking for an indication of whether or not I should be using the documented attributes. But that's just me.

**Comment by rosemariesadler** [comment]
we put most of our docs in the demo page specifically because of the web components catalog making it easy to see the demo page, so we've focused less on our jsdocs because we assume people are looking at the demo page instead of the docs page. I'll get that updated here soon.

**Comment by rosemariesadler** [comment]
I've updated the jsdocs and they will go to the component catalog with our next release.
